name: "Solution Wiper"
description:
  'Removes all solutions from exercises, solutions start with a comment "Write
  your code here" and end with the end of the scope.'
author: "Jobtrek"

# Define your inputs here.
inputs:
  path:
    description: "The path to the file or directory to wipe solutions from."
    required: false
    default: "."
  lang:
    description: "The languages of the files to wipe solutions from."
    required: false
    default: "rs,js,ts,java,php"

# Define your outputs here.
outputs:
  wiped:
    description: "The path to the file or directory with wiped solutions."

# Update the image repository and tag below.
runs:
  using: docker
  image: docker://ghcr.io/jobtrek/sw-action:v1.1.9
  env:
    INPUT_PATH: ${{ inputs.path }}
    INPUT_LANG: ${{ inputs.lang }}
